In [3]:
import os
import numpy as np
from isotherm import generateconfig, submit_mof, submit_mofs


# predefine a pressure list and generate the config files for each pressure
ff_data = "Al_graphite.json" 
cif_directory = "/home/yutao/project/elias_structures/"
pressure_list = list(np.linspace(0.1, 1.5, 20))
temperature = 298
molecule = "n2"
basename, _ = os.path.splitext(ff_data)
output_name = f"{basename}_elias_{molecule}.log"
cif_files = [file for file in os.listdir(cif_directory) if file.endswith('.cif')]

for cif_file in cif_files:
    cif_path = os.path.join(cif_directory, cif_file)
    generateconfig(ff_data, temperature, pressure_list, cif_path, output_name,molecule)
    submit_mof(output_name)

As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/elias_structures/mono_In_opt_charged.cif
The simulation temperature is:  298
This is the final pk values for isotherm workflow:  826577

As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/elias_structures/mono_Ga_opt_charged.cif
The simulation temperature is:  298
This is the final pk values for isotherm workflow:  826594

As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/elias_structures/orth_Ga_opt_charged.cif
The simulation temperature is:  298
This is the final pk values for isotherm workflow:  826611

As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/elias_structures/orth_Al_opt_charged.cif
The simulation temperature is:  298
This is the final pk values for isotherm workflow:  826628

As long 

In [2]:
# a example to submit workchains a list of mofs

from isotherm import submit_mofs
for ff_data in ["InN.json","UFF.json","Al_graphite.json","mil160_CO.json"]:
    structure_path = "/home/yutao/project/InN-MOF/"
    molecule = "co2"
    submit_mofs(structure_path,ff_data, molecule, suffix="_InN_new_short")

Go to  /home/yutao/project/InN-MOF/MMPF-7
As long as it finishes, 0
The tested force field is:  InN.json
The tested cif is:  /home/yutao/project/InN-MOF/MMPF-7/COKROL_clean.cif
The simulation temperature is:  273
This is the final pk values for isotherm workflow:  853839

Go to  /home/yutao/project/InN-MOF/ZIDDIB
As long as it finishes, 0
The tested force field is:  InN.json
The tested cif is:  /home/yutao/project/InN-MOF/ZIDDIB/RSM3919.cif
The simulation temperature is:  293
This is the final pk values for isotherm workflow:  853856

Go to  /home/yutao/project/InN-MOF/SNNU-50
As long as it finishes, 0
The tested force field is:  InN.json
The tested cif is:  /home/yutao/project/InN-MOF/SNNU-50/UDANEV_clean.cif
The simulation temperature is:  273
This is the final pk values for isotherm workflow:  853873

Go to  /home/yutao/project/InN-MOF/MMPF-8
As long as it finishes, 0
The tested force field is:  InN.json
The tested cif is:  /home/yutao/project/InN-MOF/MMPF-8/COKRUR_clean.cif
The sim

In [2]:
# a example to submit workchains a list of mofs

from isotherm import submit_mofs
for ff_data in ["UFF_scaling.json"]:
    structure_path = "/home/yutao/project/Al-MOF"
    molecule = "co2"
    submit_mofs(structure_path,ff_data, molecule)

Go to  /home/yutao/project/Al-MOF/MIL120
As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/Al-MOF/MIL120/MIL-120.cif
The simulation temperature is:  303
This is the final pk values for isotherm workflow:  848387

Go to  /home/yutao/project/Al-MOF/cau21bpdc
As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/Al-MOF/cau21bpdc/DAZMID.cif
The simulation temperature is:  298
This is the final pk values for isotherm workflow:  848404

Go to  /home/yutao/project/Al-MOF/WOJJOV
As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/Al-MOF/WOJJOV/RSM2706.cif
The simulation temperature is:  195
This is the final pk values for isotherm workflow:  848421

Go to  /home/yutao/project/Al-MOF/MIL-160
As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/Al-MOF/MIL-160/MIL-1

In [ ]:
# a example to submit workchains a list of mofs

from isotherm import submit_mofs
for ff_data in ["Al_graphite.json"]:
    structure_path = "/home/yutao/project/Al-MOF"
    molecule = "co2"
    submit_mofs(structure_path,ff_data, molecule, suffix="_0524_08")

In [3]:
import os
import numpy as np
from isotherm import generateconfig, submit_mof, submit_mofs

ff_data = "Al_graphite.json" 
cif_directory = "/home/yutao/project/elias_structures_new/"
pressure_list = list(np.linspace(0.1, 1.5, 20))
temperature = 298
molecule = "n2"
basename, _ = os.path.splitext(ff_data)
output_name = f"{basename}_elias_new_{molecule}.log"
cif_files = [file for file in os.listdir(cif_directory) if file.endswith('.cif')]

for cif_file in cif_files:
    cif_path = os.path.join(cif_directory, cif_file)
    generateconfig(ff_data, temperature, pressure_list, cif_path, output_name,molecule)
    submit_mof(output_name)

As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/elias_structures_new/orth_AlAlScSc_opt_charged.cif
The simulation temperature is:  298
This is the final pk values for isotherm workflow:  829928

As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/elias_structures_new/orth_AlScScAl_opt_charged.cif
The simulation temperature is:  298
This is the final pk values for isotherm workflow:  829945

As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/elias_structures_new/orth_AlScAlSc_opt_charged.cif
The simulation temperature is:  298
This is the final pk values for isotherm workflow:  829962

As long as it finishes, 0
The tested force field is:  Al_graphite.json
The tested cif is:  /home/yutao/project/elias_structures_new/orth_rdm_AlSc_opt_charged.cif
The simulation temperature is:  298
This is the final pk values 

In [3]:
import os
import numpy as np
from isotherm import generateconfig, submit_mof, submit_mofs

ff_data = "UFF.json" 
cif_directory = "/home/yutao/project/elias_structures/"
pressure_list = list(np.linspace(0.1, 1.5, 20))
temperature = 298

basename, _ = os.path.splitext(ff_data)
output_name = f"{basename}_elias.log"
cif_files = [file for file in os.listdir(cif_directory) if file.endswith('.cif')]

for cif_file in cif_files:
    cif_path = os.path.join(cif_directory, cif_file)
    generateconfig(ff_data, temperature, pressure_list, cif_path, output_name)
    submit_mof(output_name)

As long as it finishes, 0
The tested force field is:  UFF.json
The tested cif is:  /home/yutao/project/elias_structures/mono_In_opt_charged.cif
The simulation temperature is:  298
This is the final pk values for isotherm workflow:  821286
This is the final pk values for binding sites workflow:  821303

As long as it finishes, 0
The tested force field is:  UFF.json
The tested cif is:  /home/yutao/project/elias_structures/mono_Ga_opt_charged.cif
The simulation temperature is:  298
This is the final pk values for isotherm workflow:  821333
This is the final pk values for binding sites workflow:  821348

As long as it finishes, 0
The tested force field is:  UFF.json
The tested cif is:  /home/yutao/project/elias_structures/orth_Ga_opt_charged.cif
The simulation temperature is:  298
This is the final pk values for isotherm workflow:  821375
This is the final pk values for binding sites workflow:  821394

As long as it finishes, 0
The tested force field is:  UFF.json
The tested cif is:  /home

In [1]:
import csv
def write_to_csv(aiida_mofs, filename):
    with open(filename, 'w', newline='') as csvfile:
        fieldnames = ['cifname',  'ff_pressure(bar)' ,'ff_loading(mol/kg)']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()
        for aiida_mof in aiida_mofs:
            writer.writerow({'cifname': aiida_mof.cifname, 'ff_loading(mol/kg)': list(aiida_mof.ff_loading), 'ff_pressure(bar)': list(aiida_mof.ff_pressure)})

In [2]:
from aiidamof import AiidaMofs, plot_isotherm, write_to_csv
import numpy as np
log_name = "Al_graphite_elias_new_n2.log"
aiida_mofs = AiidaMofs(log_name)

write_to_csv(aiida_mofs, "refined_FF_elias_new_n2.csv")

No experimental isotherm found for  elias_structures_new
meet error in extract data from structure elias_structures_new
No experimental isotherm found for  elias_structures_new
meet error in extract data from structure elias_structures_new
No experimental isotherm found for  elias_structures_new
meet error in extract data from structure elias_structures_new
No experimental isotherm found for  elias_structures_new
meet error in extract data from structure elias_structures_new


In [ ]:
from aiidamof import AiidaMofs, plot_isotherm
import numpy as np
log_name = "Al_graphite_elias.log"
aiida_mofs = AiidaMofs(log_name)

write_to_csv(aiida_mofs, "refined_FF_elias.csv")

In [2]:
from aiidamof import AiidaMofs, plot_isotherm
import numpy as np
log_name = "Al_graphite_elias_n2.log"
aiida_mofs = AiidaMofs(log_name)

write_to_csv(aiida_mofs, "refined_FF_elias_n2.csv")

No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures
No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures
No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures
No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures
No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures
No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures


In [ ]:
from aiidamof import AiidaMofs, plot_isotherm
import numpy as np
log_name = "Al_graphite_elias_n2.log"
aiida_mofs = AiidaMofs(log_name)
# Get an AiidaMof object

# Print the folder of the AiidaMof object
for aiida_mof in aiida_mofs:
    print(aiida_mof.mofname)
    print(aiida_mof.ff_loading)
    print(aiida_mof.ff_pressure)

In [2]:
from aiidamof import AiidaMofs, plot_isotherm
import numpy as np
log_name = "Al_graphite_elias.log"
aiida_mofs = AiidaMofs(log_name)
# Get an AiidaMof object

# Print the folder of the AiidaMof object
for aiida_mof in aiida_mofs:
    print(aiida_mof.mofname)
    print(aiida_mof.ff_loading)
    print(aiida_mof.ff_pressure)

No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures
No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures
No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures
No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures
No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures
No experimental isotherm found for  elias_structures
meet error in extract data from structure elias_structures
elias_structures
[0.31661457060571, 0.47136338273102, 0.60169039012248, 0.70350318280704, 0.78366002968606, 0.85142025705189, 0.9297597289996, 1.0197197880993, 1.0200049965739, 1.0707323085252, 1.1208029777093, 1.1501462868191, 1.1778115088574, 1.2261510289281, 1.2633674184886, 1.2639577337035, 1.2762946584196, 1.2994496069058

In [12]:
data_points = data
sorted_points = data_points[np.argsort(data_points[:, 0])]   

In [13]:
sorted_points

array([[3.19258069e-02, 2.74059120e+00],
       [4.10347324e-02, 8.21013004e+00],
       [6.81723070e-02, 1.25323726e+01],
       [9.28526456e-02, 1.59278832e+01],
       [1.20048032e-01, 1.94375843e+01],
       [1.46880303e-01, 2.27334141e+01],
       [1.73712575e-01, 2.56878864e+01],
       [2.00544846e-01, 2.83696468e+01],
       [2.27377118e-01, 3.09231458e+01],
       [2.54209389e-01, 3.35010581e+01],
       [2.81041661e-01, 3.56854409e+01],
       [3.07873932e-01, 3.80214055e+01],
       [3.34706204e-01, 4.01915775e+01],
       [3.61538475e-01, 4.25654375e+01],
       [3.88370747e-01, 4.44632361e+01],
       [4.15203018e-01, 4.64273517e+01],
       [4.42035290e-01, 4.83085710e+01],
       [4.68867561e-01, 5.01068940e+01],
       [4.95699833e-01, 5.19810079e+01],
       [5.22532104e-01, 5.38432795e+01],
       [5.49364376e-01, 5.55871278e+01],
       [5.76196647e-01, 5.74967687e+01],
       [6.03028919e-01, 5.92240378e+01],
       [6.29861190e-01, 6.09489384e+01],
       [6.553174

In [1]:
from utils import process_csv
num_points_to_select = 20  # 要选择的数据点数量
input_csv = '/home/yutao/project/InN-MOF/MMPF-8/273K_long.csv'  # 输入CSV文件路径
output_csv = '/home/yutao/project/InN-MOF/MMPF-8/273K.csv'  # 输出CSV文件路径
process_csv(input_csv, output_csv, num_points_to_select)

input_csv = '/home/yutao/project/InN-MOF/SNNU-50/273K_long.csv'  # 输入CSV文件路径
output_csv = '/home/yutao/project/InN-MOF/SNNU-50/273K.csv'  # 输出CSV文件路径
process_csv(input_csv, output_csv, num_points_to_select)

input_csv = '/home/yutao/project/InN-MOF/MMPF-7/273K_long.csv'  # 输入CSV文件路径
output_csv = '/home/yutao/project/InN-MOF/MMPF-7/273K.csv'  # 输出CSV文件路径
process_csv(input_csv, output_csv, num_points_to_select)

input_csv = '/home/yutao/project/InN-MOF/ZIDDIB/293K_long.csv'  # 输入CSV文件路径
output_csv = '/home/yutao/project/InN-MOF/ZIDDIB/293K.csv'  # 输出CSV文件路径
process_csv(input_csv, output_csv, num_points_to_select)

TypeError: '<' not supported between instances of 'NoneType' and 'int'

In [62]:
def select_max_spacing_points(data_points, num_points_to_select):
    # 排序数据点

    sorted_points = data_points[np.argsort(data_points[:, 0])]    # 初始化选择点的列表
    if len(sorted_points) < num_points_to_select:
        num_points_to_select = len(sorted_points)
    selected_indices = [0, len(sorted_points) - 1]  # 选第一个和最后一个点的索引    # 用贪心算法选择剩余的数据点
    for _ in range(num_points_to_select - 2):  # 已经选择了两个点，还需选择 (num_points_to_select - 2) 个
        max_gap = -1
        new_index = None
        # 找到当前选点间距最大的间隔，并插入其中间的点
        for i in range(len(selected_indices) - 1):
            left_index, right_index = selected_indices[i], selected_indices[i + 1]
            left, right = sorted_points[left_index, 0], sorted_points[right_index, 0]
            # 找到 left 和 right 之间最靠近中间的点
            candidate_idx = np.searchsorted(sorted_points[:, 0], (left + right) / 2)
            '''
            if not candidate_idx:
                print(candidate_idx)
                print(sorted_points[:, 0], (left + right) / 2)
                print(np.searchsorted(sorted_points[:, 0], (left + right) / 2))
                continue
            '''
            print(candidate_idx)
            if isinstance(candidate_idx, np.ndarray):
                candidate_idx = candidate_idx[0,0]
            elif candidate_idx >= len(sorted_points):
                candidate_idx = len(sorted_points) - 1
            candidate = sorted_points[candidate_idx]
            print(candidate)
            gap = min(candidate[0] - left, right - candidate[0])
            if gap > max_gap and candidate_idx not in selected_indices:
                max_gap = gap
                new_index = candidate_idx
        if new_index is None:
            print(candidate_idx)
            print(sorted_points[:, 0], (left + right) / 2)
            print(np.searchsorted(sorted_points[:, 0], (left + right) / 2))   
        selected_indices.append(new_index)
        #selected_indices.sort()  # 保持索引有序    
    #selected_points = sorted_points[selected_indices]    
    return selected_indices#selected_points

"""
this is a example to use it
from utils import process_csv

input_csv = '/home/yutao/project/InN-MOF/MMPF-8/273K_long.csv'  # 输入CSV文件路径
output_csv = '/home/yutao/project/InN-MOF/MMPF-8/273K.csv'  # 输出CSV文件路径
num_points_to_select = 20  # 要选择的数据点数量
process_csv(input_csv, output_csv, num_points_to_select)

"""
def process_csv(input_csv, output_csv, num_points_to_select):
    # 读取CSV文件
    data = pd.read_csv(input_csv).values    # 选择数据点
    selected_points = select_max_spacing_points(data, num_points_to_select)    # 保存结果到新的CSV文件
    pd.DataFrame(selected_points).to_csv(output_csv, header=False, index=False)# 示例调用

In [63]:
data_points = pd.read_csv(input_csv).values
select_arr = select_max_spacing_points(data_points, num_points_to_select)

12
[ 5.21883979 26.87483043]
12
[ 5.21883979 26.87483043]
17
[ 7.69461011 30.98980553]
17
[0.21026274 0.38223428 0.72582606 1.11603074 1.51114975 1.95253237
 2.39364201 2.64803585 3.24442908 3.69033467 4.15165914 4.69569833
 5.21883979 5.6436568  6.14613129 6.64349435 7.18215745 7.69461011
 8.12973493 8.66314129 9.15260209 9.45829548 9.76410534] 7.491472565211229
17
12
[ 5.21883979 26.87483043]
17
[ 7.69461011 30.98980553]
[[ 8 10]]
[ 3.24442908 21.95268376]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [64]:
data_points

array([[ 0.21026274,  2.20046325],
       [ 0.38223428,  4.13382544],
       [ 0.72582606,  7.44882419],
       [ 1.11603074, 10.83814333],
       [ 1.51114975, 13.81970223],
       [ 1.95253237, 16.32701329],
       [ 2.39364201, 18.40560989],
       [ 2.64803585, 19.77207271],
       [ 3.24442908, 21.95268376],
       [ 3.69033467, 23.43763416],
       [ 4.15165914, 24.76082843],
       [ 4.69569833, 25.97637958],
       [ 5.21883979, 26.87483043],
       [ 5.6436568 , 27.7429338 ],
       [ 6.14613129, 28.68669337],
       [ 6.64349435, 29.72863599],
       [ 7.18215745, 30.62673357],
       [ 7.69461011, 30.98980553],
       [ 8.12973493, 31.79494302],
       [ 8.66314129, 32.56301139],
       [ 9.15260209, 33.30792683],
       [ 9.45829548, 33.39939024],
       [ 9.76410534, 33.67378049]])

In [46]:
input_csv = '/home/yutao/project/InN-MOF/ZIDDIB/293K_long.csv'  # 输入CSV文件路径
output_csv = '/home/yutao/project/InN-MOF/ZIDDIB/293K.csv'  # 输出CSV文件路径
process_csv(input_csv, output_csv, num_points_to_select)

22
[0.21026274 0.38223428 0.72582606 1.11603074 1.51114975 1.95253237
 2.39364201 2.64803585 3.24442908 3.69033467 4.15165914 4.69569833
 5.21883979 5.6436568  6.14613129 6.64349435 7.18215745 7.69461011
 8.12973493 8.66314129 9.15260209 9.45829548 9.76410534] 9.45835371677499
22


TypeError: '<' not supported between instances of 'NoneType' and 'int'

In [22]:
import pandas as pd
input_csv = '/home/yutao/project/InN-MOF/ZIDDIB/293K_long.csv'
data = pd.read_csv(input_csv).values 

In [15]:
data = pd.read_csv(input_csv).values 

In [16]:
select_max_spacing_points(data,20)

array([[3.19258069e-02, 2.74059120e+00],
       [9.28526456e-02, 1.59278832e+01],
       [1.20048032e-01, 1.94375843e+01],
       [1.73712575e-01, 2.56878864e+01],
       [2.27377118e-01, 3.09231458e+01],
       [2.54209389e-01, 3.35010581e+01],
       [3.07873932e-01, 3.80214055e+01],
       [3.61538475e-01, 4.25654375e+01],
       [3.88370747e-01, 4.44632361e+01],
       [4.42035290e-01, 4.83085710e+01],
       [4.95699833e-01, 5.19810079e+01],
       [5.49364376e-01, 5.55871278e+01],
       [6.29861190e-01, 6.09489384e+01],
       [6.83525733e-01, 6.43087380e+01],
       [7.37668059e-01, 6.76115729e+01],
       [7.90854819e-01, 7.07204367e+01],
       [8.71351634e-01, 7.52248630e+01],
       [9.25016177e-01, 7.82175505e+01],
       [1.00551299e+00, 8.26698705e+01],
       [1.03234526e+00, 8.41673985e+01]])